Models/ApplicationdbContext.cs
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;

namespace TP3.Models
{
    public class ApplicationdbContext : DbContext
    {
        public DbSet<Movie> Movies { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<membershiptype> Memberships { get; set; }
        public DbSet<Genre> Genre { get; set; }
        public ApplicationdbContext(DbContextOptions options)
        : base(options)
        {
        }
       protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movie>()
                 .HasOne(m => m.Genre)   // One Genre
                 .WithMany(c => c.Movies)   // has Many Movies
                 .HasForeignKey(m => m.GenreId)   // Foreign key property in Movie
                 .OnDelete(DeleteBehavior.Cascade);  // Optional: Cascade delete if desired
            base.OnModelCreating(modelBuilder);
            // Chemin du fichier JSON



            base.OnModelCreating(modelBuilder);
            string genreJsonPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Data", "Genre.json");

            string GenreJSon = System.IO.File.ReadAllText(genreJsonPath);
            List<Genre>? genres = System.Text.Json.JsonSerializer.Deserialize<List<Genre>>(GenreJSon);
            foreach (Genre c in genres)
                modelBuilder.Entity<Genre>()
                .HasData(c);

            base.OnModelCreating(modelBuilder);
            string MembershipJsonPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Data", "Membership.json");

            string MembershipJSon = System.IO.File.ReadAllText(MembershipJsonPath);
            List<membershiptype>? membershiptypes = System.Text.Json.JsonSerializer.Deserialize<List<membershiptype>>(MembershipJSon);
            foreach (membershiptype c in membershiptypes)
                modelBuilder.Entity<membershiptype>()
                .HasData(c);

        }
     

    }
}

Models/Customer.cs
namespace TP3.Models
{
    public class Customer
    {
        public Guid Id { get; set; }
        public string ?Name { get; set; }
        public string? MembershiptypeID { get; set; }
        public membershiptype? membershiptype { get; set; }
        public ICollection<Movie>? movie { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace TP3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Genre.cs
namespace TP3.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string ? GenreName { get; set; }
        public ICollection<Movie>? Movies { get; set; }  
    }
}

Models/Movie.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TP3.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string ? Title { get; set; }
        public int? GenreId { get; set; }
        public Genre? Genre { get; set; }
        public string? ImagePath { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public DateTime? addedAT { get; set; }
        public ICollection<Customer> ? Customer { get; set; }
    }
}

Models/membershiptype.cs
namespace TP3.Models
{
    public class membershiptype
    {
        public string id { get; set; }
        public string ? SignUpfee { get; set; }
        public int? DurationINMonth { get; set; }
        public float? DiscountRate { get; set; }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using TP3.Services;
using TP3.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TP3.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly IMembershipTypeService _MembershipTypeService;

        public CustomerController(ICustomerService _customerService, IMembershipTypeService membershipTypeService)
        {
            this._customerService = _customerService;
            _MembershipTypeService = membershipTypeService;
           
        }
        public IActionResult Index()
        {
            return View(_customerService.GetAll());
        }
        public IActionResult Details(Guid id)
        {
            return View(_customerService.GetById(id));


        }
        public IActionResult Delete(Guid id)
        {
               _customerService.Delete(_customerService.GetById(id));
             return RedirectToAction("Index");


        }

        public IActionResult Edit(Guid id)

        {
           var members = _MembershipTypeService.getAll();
            /*Ici on a utilise le viewBag pour pouvoire creer une liste deroulante dans le form de creation d'un user
             ou il peut choisir le nom du membership au quel il sera abonne (associe) et vu que on peut pas envoyer a une 
            seule vie plusieurs type de model donc on utlise cet methode interdmediare */
            ViewBag.member = members.Select(members => new SelectListItem()
            {
                Text = members.id.ToString(),
                Value = members.id.ToString() 
            });
            return View(_customerService.GetById(id));


        }
        public IActionResult AddCustomer(uint id) {
            var members = _MembershipTypeService.getAll();
            ViewBag.member = members.Select(members => new SelectListItem()
            {
                Text = members.id.ToString(),
                Value = members.id.ToString() 
            });
            return View();
        }
        
        public IActionResult CustomerAdd(Customer customer)
        {
            if (!ModelState.IsValid)
             {

                 return RedirectToAction("Index");
             }

             _customerService.Add(customer);
             return RedirectToAction("Index");


        }
        public IActionResult SaveCanchges(Customer customer) {
         _customerService.Update(customer);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TP3.Models;

namespace TP3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
    
        public HomeController(ILogger<HomeController> logger )
        {
            _logger = logger;
        }

      

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP3.Models;
using TP3.Services;

namespace TP3.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _IMovieService;
     private readonly IGenreRepository _GenreRepository;
        public MovieController(IMovieService IMovieService, IGenreRepository GenreRepository )
        {
            _IMovieService= IMovieService;
            _GenreRepository= GenreRepository;
        }

        public ActionResult Index()
        {
            var movies = _IMovieService.GetMovieOrdreCroissant();

            return View(movies);
        }
        public ActionResult Create()
        {
            var members = _GenreRepository.Genres();
            ViewBag.member = members.Select(members => new SelectListItem()
            {
                Text = members.GenreName.ToString(),
                Value = members.Id.ToString()
            });
            return View();
        }


        public ActionResult CreateMovie(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _IMovieService.Add(movie);
                return RedirectToAction("Index");
            }

            // Gestion des erreurs de validation
            return View("Create", movie);
        }


    }
}

Views/Customer/AddCustomer.cshtml
@model TP3.Models.Customer

@{
    ViewData["Title"] = "Add Customer";
}
    <div class="container mt-5">
        <h1 class="mb-4">Create</h1>

        <h2 class="mb-4">Customer</h2>

        <form method="post" asp-action="CustomerAdd">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input type="text" class="form-control w-50" id="Name" name="Name" required />
            </div>
            <br />
            <div class="form-group">
                <label asp-for="MembershiptypeID" class="control-label">Membership Name</label>
                <select asp-for="MembershiptypeID" class="form-control" asp-items="@(new SelectList(ViewBag.member, "Value", "Text"))"></select>
                <span asp-validation-for="MembershiptypeID" class="text-red"></span>
            </div>
            <br />

            <button type="submit" class="btn btn-primary">Add Customer</button>
        </form>

        <a href="#" class="btn btn-secondary mt-3" onclick="history.go(-1);">Cancel</a>
    </div>

Views/Customer/Details.cshtml
@model TP3.Models.Customer
@{
    ViewData["Title"] = "Details Customer";
}


    <div class="container mt-5">
        <h2 class="mb-4">Customer Details</h2>

        <dl class="row">
            <dt class="col-sm-3">ID</dt>
            <dd class="col-sm-9">@Model.Id</dd>

            <dt class="col-sm-3">Name</dt>
            <dd class="col-sm-9">@Model.Name</dd>

            <dt class="col-sm-3">Offre</dt>
            <dd class="col-sm-9">@Model.MembershiptypeID</dd>
        </dl>

        <a href="#" class="btn btn-primary" onclick="history.go(-1);">Back</a>
    </div>

    

Views/Customer/Edit.cshtml
@model TP3.Models.Customer

@{
    ViewData["Title"] = "Edit Customer";
}

    <div class="container mt-5">
        <h2 class="mb-4">Edit Customer</h2>

        <form method="post" asp-action="SaveCanchges" asp-route-id="@Model.Id">
            <div class="form-group">
                <label for="Name">Name</label>
                <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" required />
            </div>

            <div class="form-group">
                <label asp-for="MembershiptypeID" class="control-label">Membership Name</label>
                <select asp-for="MembershiptypeID" class="form-control" asp-items="@(new SelectList(ViewBag.member, "Value", "Text"))"></select>
                <span asp-validation-for="MembershiptypeID" class="text-red"></span>
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>

        <a href="#" class="btn btn-secondary mt-3" onclick="history.go(-1);">Cancel</a>
    </div>

  

Views/Customer/Index.cshtml
@model IEnumerable<TP3.Models.Customer>

@{
    ViewData["Title"] = "List Customer";
}
    <div class="container mt-5">
        <a asp-controller="Movie" asp-action="Index" class="btn btn-primary">Movie List</a>

        <a asp-action="AddCustomer" class="btn btn-primary">Add Customer</a>

        <h2 class="mb-4">Customer List</h2>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Membership</th>
                    <th>Actions</th>
                    <!-- Ajoutez d'autres colonnes selon votre modèle -->
                </tr>
            </thead>
            <tbody>
                @foreach (var customer in Model)
                {
                    <tr>
                        <td>@customer.Name</td>
                        <td>@customer.MembershiptypeID</td>
                        <td>
                            <a asp-action="Details" asp-route-id="@customer.Id">Details</a> | <a asp-action="Delete" asp-route-id="@customer.Id">Delete</a> | <a asp-action="Edit" asp-route-id="@customer.Id">Edit</a>
                        </td><!-- Ajoutez d'autres colonnes selon votre modèle -->
                    </tr>
                }
            </tbody>
        </table>
    </div>

  

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Movie/Create.cshtml
@model TP3.Models.Movie
@{
    ViewData["Title"] = "Add Movie";
}
<div class="container mt-5">

    <h1 class="mb-4">Add Movie</h1>

    <form method="post" asp-action="CreateMovie" enctype="multipart/form-data">
        <div class="form-group">
            <label for="Title">Title</label>
            <input type="text" class="form-control" id="Title" name="Title" required />
        </div>
        <br />
        <div class="form-group">
            <label asp-for="GenreId" class="control-label">Movie Genre </label>
            <select asp-for="GenreId" class="form-control" asp-items="@(new SelectList(ViewBag.member, "Value", "Text"))"></select>
            <span asp-validation-for="GenreId" class="text-red"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="addedAT" class="control-label">Release Date</label>
            <input asp-for="addedAT" type="date" class="form-control" />
            <span asp-validation-for="addedAT" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="ImageFile" class="control-label">Upload Image</label>
            <input asp-for="ImageFile" type="file" class="form-control" required />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Add Movie</button>
    </form>

    <a href="#" class="btn btn-secondary mt-3" onclick="history.go(-1);">Cancel</a>
</div>

Views/Movie/Index.cshtml
@model IEnumerable<TP3.Models.Movie>
@{
    ViewData["Title"] = "Movie List";
}


<div class="container mt-5">
    <a asp-action="Create" class="btn btn-primary">Add Movie</a>

    <h2 class="mb-4">Movie List</h2>

    <div class="row">
        @foreach (var movie in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="@movie.ImagePath" class="card-img-top movie-img height:10%" alt="Movie Image">
                    <div class="card-body">
                        <h5 class="card-title">@movie.Title</h5>
                        <p class="card-text">Genre: @movie.Genre?.GenreName</p>
                    </div>
                </div>
            </div>
        }
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC-Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TP3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name ="_Nav_Bar"/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TP3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Nav_Bar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">MVC Movie</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="index">Movies</a>
                </li>
            </ul>
        </div>
    </div>
</nav>